### PR TITLE
Release/1.2.0

### PR DESCRIPTION
**Pull request by kozalosev**
Fix some bugs, add metrics, auto registration of commands, and `/seqc` (sequence conservative) command

### CODE REVIEW

**Comment by kozalosev** [comment]
@leonardo834, hello! If you still here, on GitHub, can you look at the changes I've made in the localization file? Are they correct?

**Comment by leonardo834** [comment]
> @leonardo834, hello! If you still here, on GitHub, can you look at the changes I've made in the localization file? Are they correct?

Yes. They're fine!

**Comment by kozalosev** [comment]
> > @leonardo834, hello! If you still here, on GitHub, can you look at the changes I've made in the localization file? Are they correct?
> 
> Yes. They're fine!

Okay, thank you! Check [this new commit](https://github.com/kozalosev/kozRandBot/pull/7/commits/35d08b26d23aed7f8028170221e8e1e75e15c31d#diff-5281dab18ba22a5dfc441b3c77efb19d6c9e58d17a271cb80ec1d5e115810fcbR162-R169) too, please. I think Google Translate is pretty good, but just in case.

**Comment by leonardo834** [comment]
> > > @leonardo834, hello! If you still here, on GitHub, can you look at the changes I've made in the localization file? Are they correct?
> > 
> > 
> > Yes. They're fine!
> 
> Okay, thank you! Check [this new commit](https://github.com/kozalosev/kozRandBot/pull/7/commits/35d08b26d23aed7f8028170221e8e1e75e15c31d#diff-5281dab18ba22a5dfc441b3c77efb19d6c9e58d17a271cb80ec1d5e115810fcbR162-R169) too, please. I think Google Translate is pretty good, but just in case.

Just checked it. It's fine.

**Pull request merged**
